((function(this: any) {/* 
 
 Copyright The Closure Library Authors. 
 SPDX-License-Identifier: Apache-2.0 
*/ 
function aa(a: any){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var k="function"==typeof Object.defineProperties?Object.defineProperty:function(a: any,b: any,c: any){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a}; 
// @ts-expect-error TS(2304): Cannot find name 'global'.
function ba(a: any){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var n=ba(this),ca="function"===typeof Symbol&&"symbol"===typeof Symbol("x"),p={},da={};function q(a: any,b: any){var c=da[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]} 
// @ts-expect-error TS(7053): Element implicitly has an 'any' type because expre... Remove this comment to see the full error message
function t(a: any,b: any,c: any){if(b)a:{var d=a.split(".");a=1===d.length;var e=d[0],f;!a&&e in p?f=p:f=n;for(e=0;e<d.length-1;e++){var g=d[e];if(!(g in f))break a;f=f[g]}d=d[d.length-1];c=ca&&"es6"===c?f[d]:null;b=b(c);null!=b&&(a?k(p,d,{configurable:!0,writable:!0,value:b}):b!==c&&(da[d]=ca?n.Symbol(d):"$jscp$"+d,d=da[d],k(f,d,{configurable:!0,writable:!0,value:b})))}} 
t("String.prototype.endsWith",function(a: any){return a?a:function(this: any, b: any, c: any) {if(null==this)throw new TypeError("The 'this' value for String.prototype.endsWith must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.endsWith must not be a regular expression");void 0===c&&(c=this.length);c=Math.max(0,Math.min(c|0,this.length));for(var d=b.length;0<d&&0<c;)if(this[--c]!=b[--d])return!1;return 0>=d};},"es6"); 
// @ts-expect-error TS(7009): 'new' expression, whose target lacks a construct s... Remove this comment to see the full error message
t("Symbol",function(a: any){function b(this: any, e: any) {if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c("jscomp_symbol_"+(e||"")+"_"+d++,e)}function c(this: any, e: any, f: any) {this.a=e;k(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.a};var d=0;return b},"es6"); 
// @ts-expect-error TS(2695): Left side of comma operator is unused and has no s... Remove this comment to see the full error message
t("Symbol.iterator",function(a: any){if(a)return a;a=(0,p.Symbol)("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=n[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&k(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ea(aa(this))}})}return a},"es6");function ea(a: any){a={next:a};a[q(p.Symbol,"iterator")]=function(){return this};return a} 
// @ts-expect-error TS(7023): 'next' implicitly has return type 'any' because it... Remove this comment to see the full error message
function fa(a: any,b: any){a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[q(p.Symbol,"iterator")]=function(){return d};return d}t("Array.prototype.values",function(a: any){return a?a:function(this: any) {return fa(this,function(b: any,c: any){return c});};},"es8"); 
// @ts-expect-error TS(2571): Object is of type 'unknown'.
t("Object.values",function(a: any){return a?a:function(b: any){var c=[],d;for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&c.push(b[d]);return c};},"es8");t("Array.prototype.keys",function(a: any){return a?a:function(this: any) {return fa(this,function(b: any){return b});};},"es6");var u=this||self,ha=/^[\w+/_-]+[=]{0,2}$/,ia: any=null;function ja(a: any){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&ha.test(a)?a:""}function ka(a: any){return a};function x(a: any){a=parseFloat(a);return isNaN(a)||1<a||0>a?0:a};function la(a: any){var b=!1,c: any;return function(){b||(c=a(),b=!0);return c}};var ma=Array.prototype.some?function(a: any,b: any){return Array.prototype.some.call(a,b,void 0)}:function(a: any,b: any){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};var y: any;function na(this: any, a: any, b: any) {this.b=a===oa&&b||"";this.a=pa}var pa={};function qa(a: any){if(void 0===y){var b=null;var c=u.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:ka,createScript:ka,createScriptURL:ka})}catch(d){u.console&&u.console.error(d.message)}y=b}else y=b}a=(b=y)?b.createScriptURL(a):a;return new na(oa,a)}var oa={};var z: any;a:{var ra=u.navigator;if(ra){var ta=ra.userAgent;if(ta){z=ta;break a}}z=""};function ua(a: any,b: any){a.src=b instanceof na&&b.constructor===na&&b.a===pa?b.b:"type_error:TrustedResourceUrl";(b=a.ownerDocument&&a.ownerDocument.defaultView)&&b!=u?b=ja(b.document):(null===ia&&(ia=ja(u.document)),b=ia);b&&a.setAttribute("nonce",b)};function va(a: any){va[" "](a);return a}va[" "]=function(){};function wa(a: any){var b=document;a=String(a);"application/xhtml+xml"===b.contentType&&(a=a.toLowerCase());return b.createElement(a)};var xa=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^\\/?#]*)@)?([^\\/?#]*?)(?::([0-9]+))?(?=[\\/?#]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function ya(a: any){var b=a.match(xa);a=b[5];var c=b[6];b=b[7];var d="";a&&(d+=a);c&&(d+="?"+c);b&&(d+="#"+b);return d}function A(a: any,b: any,c: any,d: any){for(var e=c.length;0<=(b=a.indexOf(c,b))&&b<d;){var f=a.charCodeAt(b-1);if(38==f||63==f)if(f=a.charCodeAt(b+e),!f||61==f||38==f||35==f)return b;b+=e+1}return-1}var B=/#|$/; 
function C(a: any,b: any){var c=a.search(B),d=A(a,0,b,c);if(0>d)return null;var e=a.indexOf("&",d);if(0>e||e>c)e=c;d+=b.length+1;return decodeURIComponent(a.substr(d,e-d).replace(/\+/g," "));}var za=/[?&]($|#)/; 
// @ts-expect-error TS(2322): Type 'string' is not assignable to type 'number'.
function D(a: any,b: any,c: any){for(var d=a.search(B),e=0,f,g=[];0<=(f=A(a,e,b,d));)g.push(a.substring(e,f)),e=Math.min(a.indexOf("&",f)+1||d,d);g.push(a.substr(e));a=g.join("").replace(za,"$1");c=null!=c?"="+encodeURIComponent(String(c)):"";(b+=c)?(c=a.indexOf("#"),0>c&&(c=a.length),d=a.indexOf("?"),0>d||d>c?(d=c,e=""):e=a.substring(d+1,c),c=[a.substr(0,d),e,a.substr(c)],a=c[1],c[1]=b?a?a+"&"+b:b:a,b=c[0]+(c[1]?"?"+c[1]:"")+c[2]):b=a;return b};function Aa(){if(!u.crypto)return Math.random();try{var a=new Uint32Array(1);u.crypto.getRandomValues(a);return a[0]/65536/65536}catch(b){return Math.random()}}function Ba(a: any,b: any){if(a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.call(void 0,a[c],c,a)}var Da=la(function(){return ma(["Google Web Preview","Mediapartners-Google","Google-Read-Aloud","Google-Adwords"],Ca)||1E-4>Math.random()}),Ea=la(function(){return-1!=z.indexOf("MSIE")});function Ca(a: any){return-1!=z.indexOf(a)} 
function E(a: any){return /^true$/.test(a);};var Fa=x("0.20"),Ga=x("0.002"),Ha=x("0.00"),Ia=x("0.00"),Ja=x("1"),Ka=E("true"),La=E("true"),Ma=E("true"),Na=E("true"),Oa=E("true");var F: any=null;function Pa(){if(null===F){F="";try{var a="";try{a=u.top.location.hash}catch(c){a=u.location.hash}if(a){var b=a.match(/\bdeid=([\d,]+)/);F=b?b[1]:""}}catch(c){}}return F}function Qa(a: any,b: any){var c;c=(c=Pa())?(c=c.match(new RegExp("\\b("+a.join("|")+")\\b")))?c[0]:null:null;if(c)a=c;else a:{if(!Ea()&&!Da()&&(c=Math.random(),c<b)){c=Aa();a=a[Math.floor(c*a.length)];break a}a=null}return a}function Ra(a: any,b: any,c: any){""!=b&&(c?a.a.hasOwnProperty(c)&&(a.a[c]=b):a.b[b]=!0)} 
// @ts-expect-error TS(2339): Property 'TAGGING' does not exist on type '{}'.
function G(a: any,b: any,c: any){var d=H;(c?d.a.hasOwnProperty(c)&&""==d.a[c]:1)&&(a=Qa(a,b))&&Ra(d,a,c)}function I(a: any){var b=H;return b.a.hasOwnProperty(a)?b.a[a]:""}function Sa(){var a=H,b: any=[];Ba(a.b,function(c: any,d: any){b.push(d)});Ba(a.a,function(c: any){""!=c&&b.push(c)});return b};var Ta={s:2,D:13,C:14,v:16,u:17},H: any=null;function Ua(){if(H){var a=Qa(["910057690","910057691"],Ja);a?Ra(H,a,17):Ra(H,"910057692",17)}}function Va(){return!!H&&"592230571"==I(16)};var J=window,Wa=document;var Xa={};function K(a: any){Xa.TAGGING=Xa.TAGGING||[];Xa.TAGGING[a]=!0};function Ya(a: any,b: any){if(Array.prototype.indexOf)return a=a.indexOf(b),"number"==typeof a?a:-1;for(var c=0;c<a.length;c++)if(a[c]===b)return c;return-1}function Za(a: any,b: any){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(c,a[c])};var $a={};function L(a: any){return void 0==$a[a]?!1:$a[a]};var M: any=[];function N(){var a={};var b=J.google_tag_data;J.google_tag_data=void 0===b?a:b;a=J.google_tag_data;a.ics||(a.ics={entries:{},set:ab,update:bb,addListener:cb,notifyListeners:db,active:!1});return a.ics} 
function ab(a: any,b: any,c: any,d: any,e: any,f: any){var g=N();g.active=!0;if(void 0!=b){var h=g.entries;g=h[a]||{};var l=g.region;c=c&&"string"==typeof c?c.toUpperCase():void 0;d=d.toUpperCase();e=e.toUpperCase();if(c===e||(c===d?l!==e:!c&&!l)){d=!!(f&&0<f&&void 0===g.update);var m={region:c,initial:"granted"===b,update:g.update,quiet:d};h[a]=m;d&&J.setTimeout(function(){h[a]===m&&m.quiet&&(m.quiet=!1,eb(a),db(),K(2))},f)}}} 
function bb(a: any,b: any){var c=N();c.active=!0;if(void 0!=b){var d=O(a);c=c.entries;c=c[a]=c[a]||{};c.update="granted"===b;b=O(a);c.quiet?(c.quiet=!1,eb(a)):b!==d&&eb(a)}}function cb(a: any,b: any){M.push({g:a,i:b})}function eb(a: any){for(var b=0;b<M.length;++b){var c=M[b];"[object Array]"==Object.prototype.toString.call(Object(c.g))&&-1!==c.g.indexOf(a)&&(c.h=!0)}}function db(){for(var a=0;a<M.length;++a){var b=M[a];if(b.h){b.h=!1;try{b.i.call()}catch(c){}}}} 
function O(a: any){a=N().entries[a]||{};return void 0!==a.update?a.update:void 0!==a.initial?a.initial:void 0}function fb(a: any){return!(N().entries[a]||{}).quiet}function gb(){return L("gtag_cs_api")?N().active:!1}function hb(a: any,b: any){N().addListener(a,b)}function ib(a: any){function b(){for(var e=0;e<c.length;e++)if(!fb(c[e]))return!0;return!1}var c=["ad_storage"];if(b()){var d=!1;hb(c,function(){d||b()||(d=!0,a())})}else a()} 
function jb(a: any){if(!1===O("ad_storage")){var b=!1;hb(["ad_storage"],function(){!b&&O("ad_storage")&&(a(),b=!0)})}};var kb=/:[0-9]+$/;function lb(a: any,b: any){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].split("=");if(decodeURIComponent(d[0]).replace(/\+/g," ")===b)return decodeURIComponent(d.slice(1).join("=")).replace(/\+/g," ");}} 
function mb(a: any,b: any){var c="query";if("protocol"===c||"port"===c)a.protocol=nb(a.protocol)||nb(J.location.protocol);"port"===c?a.port=String(Number(a.hostname?a.port:J.location.port)||("http"==a.protocol?80:"https"==a.protocol?443:"")):"host"===c&&(a.hostname=(a.hostname||J.location.hostname).replace(kb,"").toLowerCase());var d=nb(a.protocol);c&&(c=String(c).toLowerCase());switch(c){case "url_no_fragment":b="";a&&a.href&&(b=a.href.indexOf("#"),b=0>b?a.href:a.href.substr(0,b));a=b;break;case "protocol":a= 
d;break;case "host":a=a.hostname.replace(kb,"").toLowerCase();break;case "port":a=String(Number(a.port)||("http"==d?80:"https"==d?443:""));break;case "path":a.pathname||a.hostname||K(1);a="/"==a.pathname.charAt(0)?a.pathname:"/"+a.pathname;a=a.split("/");0<=Ya([],a[a.length-1])&&(a[a.length-1]="");a=a.join("/");break;case "query":a=a.search.replace("?","");b&&(a=lb(a,b));break;case "extension":a=a.pathname.split(".");a=1<a.length?a[a.length-1]:"";a=a.split("/")[0];break;case "fragment":a=a.hash.replace("#", 
"");break;default:a=a&&a.href}return a}function nb(a: any){return a?a.replace(":","").toLowerCase():""};function ob(a: any,b: any,c: any,d: any){if(pb(d)){d=[];b=String(b||document.cookie).split(";");for(var e=0;e<b.length;e++){var f=b[e].split("="),g=f[0].replace(/^\s*|\s*$/g,"");g&&g==a&&((f=f.slice(1).join("=").replace(/^\s*|\s*$/g,""))&&c&&(f=decodeURIComponent(f)),d.push(f))}a=d}else a=[];return a}function qb(a: any,b: any,c: any,d: any){var e=document.cookie;document.cookie=a;a=document.cookie;return e!=a||void 0!=c&&0<=ob(b,a,!1,d).indexOf(c)} 
// @ts-expect-error TS(7053): Element implicitly has an 'any' type because expre... Remove this comment to see the full error message
function rb(a: any,b: any,c: any){function d(v: any,w: any,sa: any){if(null==sa)return delete g[w],v;g[w]=sa;return v+"; "+w+"="+sa}function e(v: any,w: any){if(null==w)return delete g[w],v;g[w]=!0;return v+"; "+w}if(pb(c.c)){if(void 0==b)var f=a+"=deleted; expires="+(new Date(0)).toUTCString();else c.encode&&(b=encodeURIComponent(b)),b=sb(b),f=a+"="+b;var g={};f=d(f,"path",c.path);if(c.expires instanceof Date)var h=c.expires.toUTCString();else null!=c.expires&&(h=c.expires);f=d(f,"expires",h);f=d(f,"max-age",c.G);f=d(f,"samesite",c.H); 
c.I&&(f=e(f,"secure"));h=c.domain;if("auto"===h){h=tb();for(var l=0;l<h.length;++l){var m="none"!==h[l]?h[l]:void 0,r=d(f,"domain",m);r=e(r,c.flags);if(!ub(m,c.path)&&qb(r,a,b,c.c))break}}else h&&"none"!==h&&(f=d(f,"domain",h)),f=e(f,c.flags),ub(h,c.path)||qb(f,a,b,c.c)}}function sb(a: any){a&&1200<a.length&&(a=a.substring(0,1200));return a}var vb=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,wb=/(^|\.)doubleclick\.net$/i;function ub(a: any,b: any){return wb.test(document.location.hostname)||"/"===b&&vb.test(a)} 
// @ts-expect-error TS(2322): Type 'number' is not assignable to type 'string'.
function tb(){var a=[],b=document.location.hostname.split(".");if(4===b.length){var c=b[b.length-1];if(parseInt(c,10).toString()===c)return["none"]}for(c=b.length-2;0<=c;c--)a.push(b.slice(c).join("."));b=document.location.hostname;wb.test(b)||vb.test(b)||a.push("none");return a}function pb(a: any){if(!L("gtag_cs_api")||!a||!gb())return!0;if(!fb(a))return!1;a=O(a);return null==a?!0:!!a};function xb(a: any,b: any){var c,d=a.F;null==d&&(d=7776E3);0!==d&&(c=new Date((b||(new Date).getTime())+1E3*d));return{path:a.path,domain:a.domain,flags:a.flags,encode:!0,expires:c}};var yb=/^\w+$/,zb=/^[\w-]+$/,Ab=/^~?[\w-]+$/,Bb={aw:"_aw",dc:"_dc",gf:"_gf",ha:"_ha",gp:"_gp"};function Cb(){if(!L("gtag_cs_api")||!gb())return!0;var a=O("ad_storage");return null==a?!0:!!a}function Db(a: any,b: any){fb("ad_storage")?Cb()?a():jb(a):b?K(3):ib(function(){Db(a,!0)})}function Eb(a: any,b: any){var c: any=[];if(!a.cookie)return c;a=ob(b,a.cookie,void 0,"ad_storage");if(!a||0==a.length)return c;for(b=0;b<a.length;b++){var d=Fb(a[b]);d&&-1===Ya(c,d)&&c.push(d)}return Gb(c)} 
// @ts-expect-error TS(2322): Type 'string' is not assignable to type '{ href: s... Remove this comment to see the full error message
function Hb(a: any){return a&&"string"==typeof a&&a.match(yb)?a:"_gcl"}function Ib(){var a=J.location.href,b=Wa.createElement("a");a&&(b.href=a);var c=b.pathname;"/"!==c[0]&&(a||K(1),c="/"+c);a=b.hostname.replace(kb,"");var d={href:b.href,protocol:b.protocol,host:b.host,hostname:a,pathname:c,search:b.search,hash:b.hash,port:b.port};b=mb(d,"gclid");c=mb(d,"gclsrc");a=mb(d,"dclid");b&&c||(d=d.hash.replace("#",""),b=b||lb(d,"gclid"),c=c||lb(d,"gclsrc"));return Jb(b,c,a)} 
// @ts-expect-error TS(7053): Element implicitly has an 'any' type because expre... Remove this comment to see the full error message
function Jb(a: any,b: any,c: any){function d(f: any,g: any){e[g]||(e[g]=[]);e[g].push(f)}var e={};e.gclid=a;e.gclsrc=b;e.dclid=c;if(void 0!==a&&a.match(zb))switch(b){case void 0:d(a,"aw");break;case "aw.ds":d(a,"aw");d(a,"dc");break;case "ds":d(a,"dc");break;case "3p.ds":L("gtm_3pds")&&d(a,"dc");break;case "gf":d(a,"gf");break;case "ha":d(a,"ha");break;case "gp":d(a,"gp")}c&&d(c,"dc");return e}function Kb(){var a={},b=Ib();Db(function(){return Lb(b,a)})} 
// @ts-expect-error TS(7053): Element implicitly has an 'any' type because expre... Remove this comment to see the full error message
function Lb(a: any,b: any,c: any){function d(m: any){return["GCL",l,m].join(".")}function e(m: any,r: any){m=Bb[m];m=void 0!==m?f+m:void 0;m&&(null==g.path&&(g.path="/"),g.domain||(g.domain="auto"),rb(m,r,g),h=!0)}b=b||{};var f=Hb(b.prefix);c=c||(new Date).getTime();var g=xb(b,c);g.c="ad_storage";var h=!1,l=Math.round(c/1E3);a.aw&&(!0===b.J?e("aw",d("~"+a.aw[0])):e("aw",d(a.aw[0])));a.dc&&e("dc",d(a.dc[0]));a.gf&&e("gf",d(a.gf[0]));a.ha&&e("ha",d(a.ha[0]));a.gp&&e("gp",d(a.gp[0]));return h} 
// @ts-expect-error TS(2339): Property 'prefix' does not exist on type '{}'.
function Fb(a: any){a=a.split(".");if(3==a.length&&"GCL"==a[0]&&a[1])return a[2]}function Gb(a: any){return a.filter(function(b: any){return Ab.test(b)});}function Mb(){for(var a=["aw"],b={},c=Hb(b.prefix),d={},e=0;e<a.length;e++)Bb[a[e]]&&(d[a[e]]=Bb[a[e]]);Db(function(){Za(d,function(f: any,g: any){g=ob(c+g,Wa.cookie,void 0,"ad_storage");if(g.length){g=g[0];var h=g.split(".");h=3!==h.length||"GCL"!==h[0]?0:1E3*(Number(h[1])||0);var l={};l[f]=[Fb(g)];Lb(l,b,h)}})})};var Nb=/^UA-\d+-\d+%3A[\w-]+(?:%2C[\w-]+)*(?:%3BUA-\d+-\d+%3A[\w-]+(?:%2C[\w-]+)*)*$/,Ob=/^~?[\w-]+(?:\.~?[\w-]+)*$/,Pb=/^\d+\.fls\.doubleclick\.net$/,Qb=/;gac=([^;?]+)/,Rb=/;gclaw=([^;?]+)/;function Sb(a: any,b: any){if(Pb.test(a.location.host)){if((a=a.location.href.match(Rb))&&2==a.length&&a[1].match(Ob))return a[1]}else if(a=Eb(a,(b||"_gcl")+"_aw"),0<a.length)return a.join(".");return""}function Tb(a: any){0!==Eb(document,"_gcl_aw").length||a&&0!==Eb(document,a+"_aw").length||(Kb(),Mb())};function Ub(a: any){var b=u.performance;return b&&b.timing&&b.timing[a]||0};var Vb={A:0,l:1,B:2,o:3,m:4};function P(this: any) {this.a={}}function Q(a: any,b: any,c: any){"number"===typeof c&&0<c&&(a.a[b]=Math.round(c))}function Wb(a: any){var b=P.a();var c=void 0===c?u:c;c=c.performance;Q(b,a,c&&c.now?c.now():null)}function Xb(){function a(){return Q(b,0,Ub("loadEventStart")-Ub("navigationStart"))}var b=P.a();0!=Ub("loadEventStart")?a():window.addEventListener("load",a)}function Yb(a: any,b: any){b.google_tag_manager&&b.google_tag_manager._li&&(b=b.google_tag_manager._li,Q(a,4,b.cbt),Q(a,3,b.cst))} 
// @ts-expect-error TS(2339): Property 'b' does not exist on type '{ (this: any)... Remove this comment to see the full error message
function Zb(){var a=P.a();return q(Object,"values").call(Object,Vb).map(function(b: any){return[b,a.a[b]||0]});}P.b=void 0;P.a=function(){return P.b?P.b:P.b=new P};function $b(a: any,b: any,c: any){a=ac(a,!0);if(a[b])return!1;a[b]=[];a[b][0]=c;return!0}function ac(a: any,b: any){var c=a.GooglebQhCsO;c||(c={},b&&(a.GooglebQhCsO=c));return c};var bc={},R: any=null; 
// @ts-expect-error TS(2322): Type 'string[]' is not assignable to type 'number'... Remove this comment to see the full error message
function cc(a: any){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);255<e&&(b[c++]=e&255,e>>=8);b[c++]=e}a=4;void 0===a&&(a=0);if(!R)for(R={},c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=c.concat(d[e].split(""));bc[e]=f;for(var g=0;g<f.length;g++){var h=f[g];void 0===R[h]&&(R[h]=g)}}a=bc[a];c=[];for(d=0;d<b.length;d+=3){var l=b[d],m=(e=d+1<b.length)?b[d+1]:0;h=(f=d+2<b.length)?b[d+2]:0;g=l>>2;l=(l&3)<<4|m>>4; 
// @ts-expect-error TS(2339): Property 'push' does not exist on type 'number'.
m=(m&15)<<2|h>>6;h&=63;f||(h=64,e||(m=64));c.push(a[g],a[l],a[m]||"",a[h]||"")}return c.join("")};function dc(a: any,b: any,c: any,d: any){var e=C(c,"fmt");if(d){var f=C(c,"random"),g=C(c,"label")||"";if(!f)return!1;f=cc(decodeURIComponent(g.replace(/\+/g," "))+":"+decodeURIComponent(f.replace(/\+/g," ")));if(!$b(a,f,d))return!1}e&&4!=e&&(c=D(c,"rfmt",e));e=D(c,"fmt",4);c=wa("SCRIPT");e=qa(e);ua(c,e);c.onload=function(){a.google_noFurtherRedirects&&d&&d.call&&(a.google_noFurtherRedirects=null,d())};b.getElementsByTagName("script")[0].parentElement.appendChild(c);return!0};var ec=E("true");function fc(){if("function"==typeof J.__uspapi){var a="";try{J.__uspapi("getUSPData",1,function(b: any,c: any){c&&b&&(b=b.uspString)&&/^[\da-zA-Z-]{1,20}$/.test(b)&&(a=b)})}catch(b){}return a}};var gc={id:!0,origin:!0,destination:!0,start_date:!0,end_date:!0,location_id:!0},hc="google_conversion_id google_conversion_format google_conversion_type google_conversion_order_id google_conversion_language google_conversion_value google_conversion_evaluemrc google_conversion_currency google_conversion_domain google_conversion_label google_conversion_color google_disable_viewthrough google_enable_display_cookie_match google_gtag_event_data google_remarketing_only google_conversion_linker google_tag_for_child_directed_treatment google_tag_for_under_age_of_consent google_allow_ad_personalization_signals google_restricted_data_processing google_conversion_items google_conversion_merchant_id google_user_id google_custom_params google_conversion_date google_conversion_time google_conversion_js_version onload_callback opt_image_generator google_gtm_url_processor google_conversion_page_url google_conversion_referrer_url google_gtm google_gcl_cookie_prefix google_read_gcl_cookie_opt_out google_basket_feed_country google_basket_feed_language google_basket_discount google_basket_transaction_type google_disable_merchant_reported_conversions google_additional_conversion_params google_transport_url".split(" "); 
function ic(a: any,b: any){var c=a;return function(){--c;0>=c&&b()}}function S(a: any){return null!=a?encodeURIComponent(String(a)):""}function jc(a: any){if(null!=a){a=String(a).substring(0,512);var b=a.indexOf("#");return-1==b?a:a.substring(0,b)}return""}function T(a: any,b: any){b=S(b);return""!=b&&(a=S(a),""!=a)?"&".concat(a,"=",b):""}function kc(a: any){var b=typeof a;return null==a||"object"==b||"function"==b?null:String(a).replace(/,/g,"\\,").replace(/;/g,"\\;").replace(/=/g,"\\=");} 
// @ts-expect-error TS(2322): Type 'string | null' is not assignable to type 'an... Remove this comment to see the full error message
function lc(a: any){if(!a||"object"!=typeof a||"function"==typeof a.join)return"";var b=[],c;for(c in a)if(Object.prototype.hasOwnProperty.call(a,c)){var d=a[c];if(d&&"function"==typeof d.join){for(var e=[],f=0;f<d.length;++f){var g=kc(d[f]);null!=g&&e.push(g)}d=0==e.length?null:e.join(",")}else d=kc(d);(e=kc(c))&&null!=d&&b.push(e+"="+d)}return b.join(";")} 
function mc(a: any,b: any){b=void 0===b?null:b;a=lc(a.google_custom_params);b=lc(b);b=a.concat(0<a.length&&0<b.length?";":"",b);return""==b?"":"&".concat("data=",encodeURIComponent(b))}function nc(a: any){return null==a||0!=a&&1!=a?"":T("tfcd",a)}function oc(a: any){return null==a||0!=a&&1!=a?"":T("tfua",a)}function pc(a: any){return!1===a?T("npa",1):!0===a?T("npa",0):""}function qc(a: any){return Ma?!0===a?T("rdp",1):!1===a?T("rdp",0):"":""} 
function rc(a: any){if(null!=a){a=a.toString();if(2==a.length)return T("hl",a);if(5==a.length)return T("hl",a.substring(0,2))+T("gl",a.substring(3,5))}return""}function U(a: any){return"number"!=typeof a&&"string"!=typeof a?"":S(a.toString())} 
function sc(a: any){if(!a)return"";a=a.google_conversion_items;if(!a)return"";for(var b=[],c=0,d=a.length;c<d;c++){var e=a[c],f=[];e&&(f.push(U(e.value)),f.push(U(e.quantity)),f.push(U(e.item_id)),f.push(U(e.start_date)),f.push(U(e.end_date)),b.push("("+f.join("*")+")"))}return 0<b.length?"&item="+b.join(""):""} 
// @ts-expect-error TS(2554): Expected 2 arguments, but got 1.
function tc(a: any,b: any){if(b.google_read_gcl_cookie_opt_out||b.google_remarketing_only||b.google_conversion_domain&&(!b.google_gcl_cookie_prefix||!/^_ycl/.test(b.google_gcl_cookie_prefix)))return"";var c="";if(b.google_gcl_cookie_prefix&&/^[a-zA-Z0-9_]+$/.test(b.google_gcl_cookie_prefix)&&"_gcl"!=b.google_gcl_cookie_prefix)return c=Sb(a,b.google_gcl_cookie_prefix),T("gclaw",c);(b=Sb(a))&&(c=T("gclaw",b));if(Pb.test(a.location.host))var d=(d=a.location.href.match(Qb))&&2==d.length&&d[1].match(Nb)?decodeURIComponent(d[1]): 
// @ts-expect-error TS(2322): Type 'number' is not assignable to type 'RegExp'.
"";else{if(Cb()){b=[];a=a.cookie.split(";");for(var e=/^\s*_gac_(UA-\d+-\d+)=\s*(.+?)\s*$/,f=0;f<a.length;f++){var g=a[f].match(e);g&&b.push({f:g[1],value:g[2]})}a={};if(b&&b.length)for(e=0;e<b.length;e++)f=b[e].value.split("."),"1"==f[0]&&3==f.length&&f[1]&&(a[b[e].f]||(a[b[e].f]=[]),a[b[e].f].push({timestamp:f[1],j:f[2]}));b=a}else b={};a=[];for(d in b){e=[];f=b[d];for(g=0;g<f.length;g++)e.push(f[g].j);a.push(d+":"+e.join(","))}d=0<a.length?a.join(";"):""}return c+(d?T("gac",d):"")} 
function uc(a: any,b: any,c: any){var d=[];if(a){var e=a.screen;e&&(d.push(T("u_h",e.height)),d.push(T("u_w",e.width)),d.push(T("u_ah",e.availHeight)),d.push(T("u_aw",e.availWidth)),d.push(T("u_cd",e.colorDepth)));a.history&&d.push(T("u_his",a.history.length))}c&&"function"==typeof c.getTimezoneOffset&&d.push(T("u_tz",-c.getTimezoneOffset()));b&&("function"==typeof b.javaEnabled&&d.push(T("u_java",b.javaEnabled())),b.plugins&&d.push(T("u_nplug",b.plugins.length)),b.mimeTypes&&d.push(T("u_nmime",b.mimeTypes.length))); 
return d.join("")}function vc(a: any){function b(d: any){try{return decodeURIComponent(d),!0}catch(e){return!1}}a=a?a.title:"";if(void 0==a||""==a)return"";a=encodeURIComponent(a);for(var c=256;!b(a.substr(0,c));)c--;return"&tiba="+a.substr(0,c)} 
// @ts-expect-error TS(2322): Type 'boolean' is not assignable to type 'number'.
function wc(a: any,b: any,c: any,d: any){var e="";if(b){if(a.top==a)var f=0;else{var g=a.location.ancestorOrigins;if(g)f=g[g.length-1]==a.location.origin?1:2;else{g=a.top;try{var h;if(h=!!g&&null!=g.location.href)c:{try{va(g.foo);h=!0;break c}catch(l){}h=!1}f=h}catch(l){f=!1}f=f?1:2}}a=c?c:1==f?a.top.location.href:a.location.href;e+=T("frm",f);e+=T("url",jc(a));e+=T("ref",jc(d||b.referrer))}return e} 
function V(a: any,b: any,c: any,d: any,e: any,f: any){f=void 0===f?null:f;var g="https://",h="landing"===d.google_conversion_type?"/extclk":"/";switch(e){default:return"";case 2:case 3:var l="googleads.g.doubleclick.net/";var m="pagead/viewthroughconversion/";break;case 1:l="www.google.com/";m="pagead/1p-conversion/";break;case 0:l=d.google_conversion_domain||"www.googleadservices.com/",m="pagead/conversion/"}Ka&&d.google_transport_url&&(l=d.google_transport_url);"/"!==l[l.length-1]&&(l+="/");if(0===l.indexOf("http://")||0=== 
l.indexOf("https://"))g="";g=[g,l,m,S(d.google_conversion_id),h,"?random=",S(d.google_conversion_time)].join("");f=void 0===f?null:f;a=[T("cv",d.google_conversion_js_version),T("fst",d.google_conversion_first_time),T("num",d.google_conversion_snippets),T("fmt",d.google_conversion_format),d.google_remarketing_only?T("userId",d.google_user_id):"",nc(d.google_tag_for_child_directed_treatment),oc(d.google_tag_for_under_age_of_consent),pc(d.google_allow_ad_personalization_signals),qc(d.google_restricted_data_processing), 
T("value",d.google_conversion_value),T("evaluemrc",d.google_conversion_evaluemrc),T("currency_code",d.google_conversion_currency),T("label",d.google_conversion_label),T("oid",d.google_conversion_order_id),T("bg",d.google_conversion_color),rc(d.google_conversion_language),T("guid","ON"),!d.google_conversion_domain&&"GooglemKTybQhCsO"in u&&"function"==typeof u.GooglemKTybQhCsO?T("resp","GooglemKTybQhCsO"):"",T("disvt",d.google_disable_viewthrough),T("eid",Sa().join()),uc(a,b,d.google_conversion_date), 
T("gtm",d.google_gtm),b&&b.sendBeacon?T("sendb","1"):"",xc(),T("ig",/googleadservices\.com/.test("www.google.com")?1:0),mc(d,f),tc(c,d),wc(a,c,d.google_conversion_page_url,d.google_conversion_referrer_url),vc(c),d.google_remarketing_only||!d.google_additional_conversion_params?"":yc(d.google_additional_conversion_params),"&hn="+S("www.google.com"),zc(a)].join("");b=Pa();a+=0<b.length?"&debug_experiment_id="+b:"";d.google_remarketing_only||d.google_conversion_domain?d=a:(Ac(d)&&!d.google_basket_transaction_type&& 
(d.google_basket_transaction_type="mrc"),b=[T("mid",d.google_conversion_merchant_id),T("fcntr",d.google_basket_feed_country),T("flng",d.google_basket_feed_language),T("dscnt",d.google_basket_discount),T("bttype",d.google_basket_transaction_type)].join(""),d=[a,b,sc(d)].join(""),d=4E3<d.length?[a,T("item","elngth")].join(""):d);g+=d;1===e?g+=[T("gcp",1),T("sscte",1),T("ct_cookie_present",1)].join(""):3==e&&(g+=T("gcp",1),g+=T("ct_cookie_present",1));La&&(e=fc(),void 0!==e&&(g+=T("us_privacy",e||"error"))); 
return g}function Bc(a: any){if(!ec){var b=wa("IFRAME");b.style.display="none";b.src="https://bid.g.doubleclick.net/xbbe/pixel?d=KAE";a.body.appendChild(b)}}function Cc(){return new Image} 
function W(a: any,b: any,c: any,d: any){var e=c.onload_callback,f;e&&e.call?f=e:f=function(){};d+=T("async","1");e=c.google_gtm_url_processor;"function"==typeof e&&(d=e(d));var g=(e=c.opt_image_generator)&&e.call,h;if(!(h=g||!1)){if(c.google_conversion_domain)var l=!1;else try{l=dc(a,b,d,f)}catch(m){l=!1}h=!l}h&&(a=Cc,g&&(a=e),a=a(),a.src=d,a.onload=f)} 
// @ts-expect-error TS(2322): Type 'string' is not assignable to type 'number'.
function Dc(a: any){for(var b=wa("IFRAME"),c=[],d=[],e=0;e<a.google_conversion_items.length;e++){var f=a.google_conversion_items[e];f&&f.quantity&&(f.sku||f.item_id)&&(c.push(f.sku||f.item_id),d.push(f.quantity))}e="";null!=a.google_basket_feed_language&&null!=a.google_basket_feed_country?e="&mrc_language="+a.google_basket_feed_language.toString()+"&mrc_country="+a.google_basket_feed_country.toString():null!=a.google_conversion_language&&(f=a.google_conversion_language.toString(),5==f.length&&(e="&mrc_language="+ 
f.substring(0,2)+"&mrc_country="+f.substring(3,5)));b.src="https://www.google.com/ads/mrc?sku="+c.join(",")+"&qty="+d.join(",")+"&oid="+a.google_conversion_order_id+"&mcid="+a.google_conversion_merchant_id+e;b.style.width="1px";b.style.height="1px";b.style.display="none";return b}function Ec(a: any,b: any,c: any){function d(){c.documentElement.appendChild(Dc(b))}"complete"===c.readyState?d():a.addEventListener?a.addEventListener("load",d):a.attachEvent("onload",d)} 
function Fc(a: any,b: any){H&&"376635471"==I(2)&&("complete"===b.readyState?Bc(b):a.addEventListener?a.addEventListener("load",function(){Bc(b)}):a.attachEvent("onload",function(){Bc(b)}))}function Ac(a: any){return!a.google_disable_merchant_reported_conversions&&!!a.google_conversion_merchant_id&&!!a.google_conversion_order_id&&!!a.google_conversion_items} 
function Gc(a: any){if("landing"==a.google_conversion_type||!a.google_conversion_id||a.google_remarketing_only&&a.google_disable_viewthrough)return!1;a.google_conversion_date=new Date;a.google_conversion_time=a.google_conversion_date.getTime();a.google_conversion_snippets="number"==typeof a.google_conversion_snippets&&0<a.google_conversion_snippets?a.google_conversion_snippets+1:1;"number"!=typeof a.google_conversion_first_time&&(a.google_conversion_first_time=a.google_conversion_time);a.google_conversion_js_version= 
// @ts-expect-error TS(7053): Element implicitly has an 'any' type because expre... Remove this comment to see the full error message
"9";0!=a.google_conversion_format&&1!=a.google_conversion_format&&2!=a.google_conversion_format&&3!=a.google_conversion_format&&(a.google_conversion_format=3);!1!==a.google_enable_display_cookie_match&&(a.google_enable_display_cookie_match=!0);return!0}function Hc(a: any,b: any){function c(f: any){d[f]=b&&null!=b[f]?b[f]:a[f]}for(var d={},e=0;e<hc.length;e++)c(hc[e]);c("onload_callback");return d} 
// @ts-expect-error TS(2538): Type 'undefined' cannot be used as an index type.
function Ic(a: any){for(var b={},c=0;c<a.length;c++){var d=a[c],e=void 0;d.hasOwnProperty("google_business_vertical")?(e=d.google_business_vertical,b[e]=b[e]||{google_business_vertical:e}):(e="",Object.prototype.hasOwnProperty.call(b,e)||(b[e]={}));e=b[e];for(var f=q(Object,"keys").call(Object,d).filter(function(l: any){return gc.hasOwnProperty(l)}),g=0;g<f.length;g++){var h=f[g];h in e||(e[h]=[]);e[h].push(d[h])}}return q(Object,"values").call(Object,b)} 
function xc(){var a="";Va()&&(a=Zb().map(function(b: any){return b.join("-")}).join("_"));return T("li",a)}function zc(a: any){if(!Oa||!a.__gsaExp||!a.__gsaExp.id)return"";a=a.__gsaExp.id;if("function"!=typeof a)return"";try{var b=Number(a());return isNaN(b)?"":T("gsaexp",b)}catch(c){return""}}function yc(a: any){var b="",c;for(c in a)a.hasOwnProperty(c)&&(b+=T(c,a[c]));return b};function Jc(a: any,b: any,c: any,d: any){Va()&&(Wb(2),d.google_gtm&&Yb(P.a(),a));var e=!1;if(!d||3!=d.google_conversion_format)return!1;try{if(Gc(d)){d.google_remarketing_only&&d.google_enable_display_cookie_match&&!ec&&H&&G(["376635470","376635471"],Fa,2);d.google_remarketing_only&&!d.google_conversion_domain&&H&&G(["759238990","759238991"],Ia,13);!d.google_remarketing_only||d.google_conversion_domain||H&&("759248991"==I(14)||"759248990"==I(14))||H&&G(["759248990","759248991"],Ha,14);!1===d.google_conversion_linker|| 
d.google_gtm||Tb(d.google_gcl_cookie_prefix);if(1==d.google_remarketing_only&&null!=d.google_gtag_event_data&&null!=d.google_gtag_event_data.items&&d.google_gtag_event_data.items.constructor===Array&&0<d.google_gtag_event_data.items.length)Kc(a,b,c,d);else{var f=!1;!d.google_remarketing_only&&q("www.google.com","endsWith").call("www.google.com","google.com")&&(Na?f=!0:(Ua(),f=!!H&&"910057691"==I(17)));f?(d.onload_callback&&"function"==typeof d.onload_callback.call?d.onload_callback=ic(2,d.onload_callback): 
// @ts-expect-error TS(2554): Expected 6 arguments, but got 5.
d.onload_callback=function(){},W(a,c,d,V(a,b,c,d,1)),W(a,c,d,V(a,b,c,d,3))):W(a,c,d,V(a,b,c,d,d.google_remarketing_only?2:0))}d.google_remarketing_only&&d.google_enable_display_cookie_match&&Fc(a,c);e=!0}Ac(d)&&(Ec(a,d,c),e=!0)}catch(g){}return e} 
// @ts-expect-error TS(7009): 'new' expression, whose target lacks a construct s... Remove this comment to see the full error message
function Kc(a: any,b: any,c: any,d: any){var e=Ic(d.google_gtag_event_data.items);d.onload_callback&&"function"==typeof d.onload_callback.call?d.onload_callback=ic(e.length,d.onload_callback):d.onload_callback=function(){};for(var f=0;f<e.length;f++)W(a,c,d,V(a,b,c,d,2,e[f])),d.google_conversion_time=d.google_conversion_time+1};H=new function(this: any) {var a=[],b=0,c;for(c in Ta)a[b++]=Ta[c];this.b={};this.a={};a=a||[];b=0;for(c=a.length;b<c;++b)this.a[a[b]]=""};G(["592230570","592230571"],Ga,16);Va()&&(Wb(1),Xb()); 
// @ts-expect-error TS(2345): Argument of type 'string | null' is not assignable... Remove this comment to see the full error message
function Lc(a: any,b: any,c: any){function d(m: any,r: any){var v=new Image;v.onload=m;v.src=r}function e(){--f;if(0>=f){var m=ac(a,!1),r=m[b];r&&(delete m[b],(m=r[0])&&m.call&&m())}}var f=c.length+1;if(2==c.length){var g=c[0],h=c[1];0<=A(g,0,"rmt_tld",g.search(B))&&0<=A(g,0,"ipr",g.search(B))&&!h.match(xa)[6]&&(h+=ya(g),c[1]=D(h,"rmt_tld","1"))}for(g=0;g<c.length;g++){h=c[g];var l=C(h,"fmt");switch(parseInt(l,10)){case 1:case 2:(l=a.document.getElementById("goog_conv_iframe"))&&!l.src?(l.onload=e,l.src=h):d(e,h);break;case 4:dc(a, 
// @ts-expect-error TS(7053): Element implicitly has an 'any' type because expre... Remove this comment to see the full error message
a.document,h,e);break;case 5:if(a.navigator&&a.navigator.sendBeacon)if(a.navigator.sendBeacon(h,"")){e();break}else h=D(h,"sendb",2);h=D(h,"fmt",3);default:d(e,h)}}e()}var X=["GooglemKTybQhCsO"],Y=u;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||void 0===Lc?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=Lc; 
// @ts-expect-error TS(2339): Property 'google_trackConversion' does not exist o... Remove this comment to see the full error message
window.google_trackConversion=function(a: any){var b=window,c=navigator,d=document;a=Hc(b,a);a.google_conversion_format=3;$a.gtag_cs_api=!!a.google_gtm;return Jc(b,c,d,a)};})).call(this);
