#!/bin/bash
function ctrl_c() {
    cat head1.alx
    cat religionen.js
    cat head2.alx
    cat middle.alx
    cat footer.alx
}
trap ctrl_c INT
./reta -spalten --alles --breite=0 -ausgabe --art=html --onetable --nocolor > middle.alx
ctrl_c
